// flow-typed signature: 81ca53f0f1265674ea291f24356dcc38
// flow-typed version: <<STUB>>/json-beautify_v^1.1.1/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-beautify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-beautify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-beautify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-beautify/index' {
  declare module.exports: $Exports<'json-beautify'>;
}
declare module 'json-beautify/index.js' {
  declare module.exports: $Exports<'json-beautify'>;
}
declare module 'json-beautify/test.js' {
  declare module.exports: $Exports<'json-beautify/test'>;
}
